default: &default
  # xpath relativo dall'interno dei tag //licences 
  own_component_tag_xpath: license/name
  own_component_tag_value: "Lispa License"
  # espressione regolare x validazione email utenti
  users_email_domain_validation_regex: lispa.it$

development:
  <<: *default
  alice_logger_path: log/alice_devel.log

test:
  <<: *default
  alice_logger_path: log/alice_test.log

production:
  <<: *default
  alice_logger_path: log/alice_prod.log
