default: &default
  # xpath relativo dall'interno dei tag //licences 
  own_component_tag_xpath: license/name
  own_component_tag_value: "Ariaspa License"
  # espressione regolare x validazione email utenti
  users_email_domain_validation_regex: ariaspa.it$
  alice_logger_path: "../data/"
  txt_logging: true
  db_logging: true
  # mail list per controllo modifiche utenti
  spy_mail_list: ""
  # logo stregatto al posto di alice
  cheshire_cat: false
  motto: "Sii ciò che sembri!"
  
development:
  <<: *default
  alice_logger_name: alice_devel.log
  cheshire_cat: true
  
test:
  <<: *default
  alice_logger_name: alice_test.log

preit:
  <<: *default
  alice_logger_name: alice_prod.log
  cheshire_cat: true
  motto: "Le modifiche che qui fai ... domani non le vedrai!"

production:
  <<: *default
  alice_logger_name: alice_prod.log
  spy_mail_list: "release.management@ariaspa.it"
